version: '3.8'

services:
  web:
    build:
      context: .
    ports:
    - 3000:3000
    volumes:
    - ./src/:/app_wd/src
    networks:
      - web_dev-net

networks:
  web_dev-net:
    external:
      name: dev-net

